host: "0.0.0.0"
port: "8080"
recommender_addr: "localhost:50051"

log:
  level: "info" # debug | info | warn | error
  format: "json" # json | text

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

database:
  host: "localhost"
  port: 5432
  user: "sci_vault"
  password: "sci_vault_secret"
  db_name: "sci_vault"
  ssl_mode: "disable"
  timezone: "UTC"
