host: "0.0.0.0"
port: "8080"
recommender_addr: "localhost:50051"

log:
  level: "info" # debug | info | warn | error
  format: "json" # json | text

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

database:
  host: "localhost"
  port: 5432
  user: "sci_vault"
  password: "sci_vault_secret"
  db_name: "sci_vault"
  ssl_mode: "disable"
  timezone: "UTC"

mailer:
  host: "smtp.example.com"
  port: 587
  username: "your-email@example.com"
  password: "your-password"

jwt:
  secret: "your-256-bit-secret"
  timeout: 24 # hours

storage:
  endpoint: "http://localhost:9000"
  access_key: "generated_access_key_from_rustfs_console" # Please replace with your actual access key
  secret_key: "generated_secret_key_from_rustfs_console" # Please replace with your actual access secret
  private_bucket: "sci-vault"
  public_bucket: "public-assets"
  use_ssl: false
