// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: recommender/v1/recommender.proto

package recommender

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommenderService_Health_FullMethodName           = "/recommender.v1.RecommenderService/Health"
	RecommenderService_EnrichDocument_FullMethodName   = "/recommender.v1.RecommenderService/EnrichDocument"
	RecommenderService_TranslateText_FullMethodName    = "/recommender.v1.RecommenderService/TranslateText"
	RecommenderService_SemanticSearch_FullMethodName   = "/recommender.v1.RecommenderService/SemanticSearch"
	RecommenderService_RecommendSimilar_FullMethodName = "/recommender.v1.RecommenderService/RecommendSimilar"
	RecommenderService_RecommendForUser_FullMethodName = "/recommender.v1.RecommenderService/RecommendForUser"
)

// RecommenderServiceClient is the client API for RecommenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecommenderService exposes operations of the recommendation engine.
type RecommenderServiceClient interface {
	// Health returns the liveness status of the recommender service.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// EnrichDocument triggers async enrichment (authors, summary, tags, embedding)
	// for the given document. Returns immediately with accepted=true; the actual
	// processing happens in the background and status is tracked via Redis.
	EnrichDocument(ctx context.Context, in *EnrichDocumentRequest, opts ...grpc.CallOption) (*EnrichDocumentResponse, error)
	// TranslateText translates the given text into the target language using LLM,
	// streaming back translated chunks as they are generated.
	TranslateText(ctx context.Context, in *TranslateTextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranslateTextResponse], error)
	// SemanticSearch embeds the query text (RETRIEVAL_QUERY task type) and
	// searches for similar documents in the vector space (cosine similarity).
	// If vector similarity is sparse, fallback to keyword search based on remaining count of results to return.
	// Access control is enforced: only private docs owned by the user and
	// lab-visible docs in the given lab are considered.
	SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error)
	// RecommendSimilar returns documents most similar to a source document,
	// ranked by vector cosine similarity against the source's stored embedding.
	// The source doc is always excluded from results. Access control mirrors
	// SemanticSearch: only private docs owned by the caller and lab-visible
	// docs in the given lab are candidates.
	RecommendSimilar(ctx context.Context, in *RecommendSimilarRequest, opts ...grpc.CallOption) (*RecommendSimilarResponse, error)
	// RecommendForUser builds a personalized ranked feed for the caller using
	// their like history, recent view history, and recent search queries as
	// preference signals. Per-signal embeddings are aggregated into a weighted
	// profile vector and nearest neighbors are returned. Liked docs are
	// excluded from the result set. Access control mirrors RecommendSimilar.
	RecommendForUser(ctx context.Context, in *RecommendForUserRequest, opts ...grpc.CallOption) (*RecommendForUserResponse, error)
}

type recommenderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommenderServiceClient(cc grpc.ClientConnInterface) RecommenderServiceClient {
	return &recommenderServiceClient{cc}
}

func (c *recommenderServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RecommenderService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommenderServiceClient) EnrichDocument(ctx context.Context, in *EnrichDocumentRequest, opts ...grpc.CallOption) (*EnrichDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichDocumentResponse)
	err := c.cc.Invoke(ctx, RecommenderService_EnrichDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommenderServiceClient) TranslateText(ctx context.Context, in *TranslateTextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TranslateTextResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecommenderService_ServiceDesc.Streams[0], RecommenderService_TranslateText_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranslateTextRequest, TranslateTextResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecommenderService_TranslateTextClient = grpc.ServerStreamingClient[TranslateTextResponse]

func (c *recommenderServiceClient) SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SemanticSearchResponse)
	err := c.cc.Invoke(ctx, RecommenderService_SemanticSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommenderServiceClient) RecommendSimilar(ctx context.Context, in *RecommendSimilarRequest, opts ...grpc.CallOption) (*RecommendSimilarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendSimilarResponse)
	err := c.cc.Invoke(ctx, RecommenderService_RecommendSimilar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommenderServiceClient) RecommendForUser(ctx context.Context, in *RecommendForUserRequest, opts ...grpc.CallOption) (*RecommendForUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendForUserResponse)
	err := c.cc.Invoke(ctx, RecommenderService_RecommendForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommenderServiceServer is the server API for RecommenderService service.
// All implementations must embed UnimplementedRecommenderServiceServer
// for forward compatibility.
//
// RecommenderService exposes operations of the recommendation engine.
type RecommenderServiceServer interface {
	// Health returns the liveness status of the recommender service.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// EnrichDocument triggers async enrichment (authors, summary, tags, embedding)
	// for the given document. Returns immediately with accepted=true; the actual
	// processing happens in the background and status is tracked via Redis.
	EnrichDocument(context.Context, *EnrichDocumentRequest) (*EnrichDocumentResponse, error)
	// TranslateText translates the given text into the target language using LLM,
	// streaming back translated chunks as they are generated.
	TranslateText(*TranslateTextRequest, grpc.ServerStreamingServer[TranslateTextResponse]) error
	// SemanticSearch embeds the query text (RETRIEVAL_QUERY task type) and
	// searches for similar documents in the vector space (cosine similarity).
	// If vector similarity is sparse, fallback to keyword search based on remaining count of results to return.
	// Access control is enforced: only private docs owned by the user and
	// lab-visible docs in the given lab are considered.
	SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error)
	// RecommendSimilar returns documents most similar to a source document,
	// ranked by vector cosine similarity against the source's stored embedding.
	// The source doc is always excluded from results. Access control mirrors
	// SemanticSearch: only private docs owned by the caller and lab-visible
	// docs in the given lab are candidates.
	RecommendSimilar(context.Context, *RecommendSimilarRequest) (*RecommendSimilarResponse, error)
	// RecommendForUser builds a personalized ranked feed for the caller using
	// their like history, recent view history, and recent search queries as
	// preference signals. Per-signal embeddings are aggregated into a weighted
	// profile vector and nearest neighbors are returned. Liked docs are
	// excluded from the result set. Access control mirrors RecommendSimilar.
	RecommendForUser(context.Context, *RecommendForUserRequest) (*RecommendForUserResponse, error)
	mustEmbedUnimplementedRecommenderServiceServer()
}

// UnimplementedRecommenderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommenderServiceServer struct{}

func (UnimplementedRecommenderServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRecommenderServiceServer) EnrichDocument(context.Context, *EnrichDocumentRequest) (*EnrichDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichDocument not implemented")
}
func (UnimplementedRecommenderServiceServer) TranslateText(*TranslateTextRequest, grpc.ServerStreamingServer[TranslateTextResponse]) error {
	return status.Error(codes.Unimplemented, "method TranslateText not implemented")
}
func (UnimplementedRecommenderServiceServer) SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SemanticSearch not implemented")
}
func (UnimplementedRecommenderServiceServer) RecommendSimilar(context.Context, *RecommendSimilarRequest) (*RecommendSimilarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendSimilar not implemented")
}
func (UnimplementedRecommenderServiceServer) RecommendForUser(context.Context, *RecommendForUserRequest) (*RecommendForUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendForUser not implemented")
}
func (UnimplementedRecommenderServiceServer) mustEmbedUnimplementedRecommenderServiceServer() {}
func (UnimplementedRecommenderServiceServer) testEmbeddedByValue()                            {}

// UnsafeRecommenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommenderServiceServer will
// result in compilation errors.
type UnsafeRecommenderServiceServer interface {
	mustEmbedUnimplementedRecommenderServiceServer()
}

func RegisterRecommenderServiceServer(s grpc.ServiceRegistrar, srv RecommenderServiceServer) {
	// If the following call panics, it indicates UnimplementedRecommenderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommenderService_ServiceDesc, srv)
}

func _RecommenderService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommenderService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommenderService_EnrichDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServiceServer).EnrichDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommenderService_EnrichDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServiceServer).EnrichDocument(ctx, req.(*EnrichDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommenderService_TranslateText_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranslateTextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecommenderServiceServer).TranslateText(m, &grpc.GenericServerStream[TranslateTextRequest, TranslateTextResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecommenderService_TranslateTextServer = grpc.ServerStreamingServer[TranslateTextResponse]

func _RecommenderService_SemanticSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServiceServer).SemanticSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommenderService_SemanticSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServiceServer).SemanticSearch(ctx, req.(*SemanticSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommenderService_RecommendSimilar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendSimilarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServiceServer).RecommendSimilar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommenderService_RecommendSimilar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServiceServer).RecommendSimilar(ctx, req.(*RecommendSimilarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommenderService_RecommendForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServiceServer).RecommendForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommenderService_RecommendForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServiceServer).RecommendForUser(ctx, req.(*RecommendForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommenderService_ServiceDesc is the grpc.ServiceDesc for RecommenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommender.v1.RecommenderService",
	HandlerType: (*RecommenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _RecommenderService_Health_Handler,
		},
		{
			MethodName: "EnrichDocument",
			Handler:    _RecommenderService_EnrichDocument_Handler,
		},
		{
			MethodName: "SemanticSearch",
			Handler:    _RecommenderService_SemanticSearch_Handler,
		},
		{
			MethodName: "RecommendSimilar",
			Handler:    _RecommenderService_RecommendSimilar_Handler,
		},
		{
			MethodName: "RecommendForUser",
			Handler:    _RecommenderService_RecommendForUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranslateText",
			Handler:       _RecommenderService_TranslateText_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "recommender/v1/recommender.proto",
}
