// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: recommender/v1/recommender.proto

package recommender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthRequest is an empty message used for health check requests.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_recommender_v1_recommender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_v1_recommender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_recommender_v1_recommender_proto_rawDescGZIP(), []int{0}
}

// HealthResponse contains the status of the recommender service.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is "ok" when the service is healthy.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// service identifies the responding service.
	Service       string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_recommender_v1_recommender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_v1_recommender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_recommender_v1_recommender_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// EnrichDocumentRequest carries the document to be enriched.
type EnrichDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// doc_id is the database primary key of the document.
	DocId uint64 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	// file_key is the S3 object key for the uploaded PDF.
	FileKey       string `protobuf:"bytes,2,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichDocumentRequest) Reset() {
	*x = EnrichDocumentRequest{}
	mi := &file_recommender_v1_recommender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichDocumentRequest) ProtoMessage() {}

func (x *EnrichDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_v1_recommender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichDocumentRequest.ProtoReflect.Descriptor instead.
func (*EnrichDocumentRequest) Descriptor() ([]byte, []int) {
	return file_recommender_v1_recommender_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichDocumentRequest) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *EnrichDocumentRequest) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

// EnrichDocumentResponse is the immediate ACK returned by the Python service.
type EnrichDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is true when the enrichment job was successfully queued.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichDocumentResponse) Reset() {
	*x = EnrichDocumentResponse{}
	mi := &file_recommender_v1_recommender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichDocumentResponse) ProtoMessage() {}

func (x *EnrichDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_v1_recommender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichDocumentResponse.ProtoReflect.Descriptor instead.
func (*EnrichDocumentResponse) Descriptor() ([]byte, []int) {
	return file_recommender_v1_recommender_proto_rawDescGZIP(), []int{3}
}

func (x *EnrichDocumentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// TranslateTextRequest carries the text to translate and the target language.
type TranslateTextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the source text to translate.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// target_language is the BCP-47 language tag (e.g. "zh-CN", "ja", "ko").
	TargetLanguage string `protobuf:"bytes,2,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateTextRequest) Reset() {
	*x = TranslateTextRequest{}
	mi := &file_recommender_v1_recommender_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateTextRequest) ProtoMessage() {}

func (x *TranslateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_v1_recommender_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateTextRequest.ProtoReflect.Descriptor instead.
func (*TranslateTextRequest) Descriptor() ([]byte, []int) {
	return file_recommender_v1_recommender_proto_rawDescGZIP(), []int{4}
}

func (x *TranslateTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateTextRequest) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

// TranslateTextResponse carries a chunk of translated text in a streaming response.
type TranslateTextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk is a piece of the translated text.
	Chunk         string `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateTextResponse) Reset() {
	*x = TranslateTextResponse{}
	mi := &file_recommender_v1_recommender_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateTextResponse) ProtoMessage() {}

func (x *TranslateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_v1_recommender_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateTextResponse.ProtoReflect.Descriptor instead.
func (*TranslateTextResponse) Descriptor() ([]byte, []int) {
	return file_recommender_v1_recommender_proto_rawDescGZIP(), []int{5}
}

func (x *TranslateTextResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

var File_recommender_v1_recommender_proto protoreflect.FileDescriptor

const file_recommender_v1_recommender_proto_rawDesc = "" +
	"\n" +
	" recommender/v1/recommender.proto\x12\x0erecommender.v1\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"I\n" +
	"\x15EnrichDocumentRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\x12\x19\n" +
	"\bfile_key\x18\x02 \x01(\tR\afileKey\"4\n" +
	"\x16EnrichDocumentResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"S\n" +
	"\x14TranslateTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12'\n" +
	"\x0ftarget_language\x18\x02 \x01(\tR\x0etargetLanguage\"-\n" +
	"\x15TranslateTextResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk2\x9e\x02\n" +
	"\x12RecommenderService\x12G\n" +
	"\x06Health\x12\x1d.recommender.v1.HealthRequest\x1a\x1e.recommender.v1.HealthResponse\x12_\n" +
	"\x0eEnrichDocument\x12%.recommender.v1.EnrichDocumentRequest\x1a&.recommender.v1.EnrichDocumentResponse\x12^\n" +
	"\rTranslateText\x12$.recommender.v1.TranslateTextRequest\x1a%.recommender.v1.TranslateTextResponse0\x01B!Z\x1fgateway/internal/pb/recommenderb\x06proto3"

var (
	file_recommender_v1_recommender_proto_rawDescOnce sync.Once
	file_recommender_v1_recommender_proto_rawDescData []byte
)

func file_recommender_v1_recommender_proto_rawDescGZIP() []byte {
	file_recommender_v1_recommender_proto_rawDescOnce.Do(func() {
		file_recommender_v1_recommender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommender_v1_recommender_proto_rawDesc), len(file_recommender_v1_recommender_proto_rawDesc)))
	})
	return file_recommender_v1_recommender_proto_rawDescData
}

var file_recommender_v1_recommender_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_recommender_v1_recommender_proto_goTypes = []any{
	(*HealthRequest)(nil),          // 0: recommender.v1.HealthRequest
	(*HealthResponse)(nil),         // 1: recommender.v1.HealthResponse
	(*EnrichDocumentRequest)(nil),  // 2: recommender.v1.EnrichDocumentRequest
	(*EnrichDocumentResponse)(nil), // 3: recommender.v1.EnrichDocumentResponse
	(*TranslateTextRequest)(nil),   // 4: recommender.v1.TranslateTextRequest
	(*TranslateTextResponse)(nil),  // 5: recommender.v1.TranslateTextResponse
}
var file_recommender_v1_recommender_proto_depIdxs = []int32{
	0, // 0: recommender.v1.RecommenderService.Health:input_type -> recommender.v1.HealthRequest
	2, // 1: recommender.v1.RecommenderService.EnrichDocument:input_type -> recommender.v1.EnrichDocumentRequest
	4, // 2: recommender.v1.RecommenderService.TranslateText:input_type -> recommender.v1.TranslateTextRequest
	1, // 3: recommender.v1.RecommenderService.Health:output_type -> recommender.v1.HealthResponse
	3, // 4: recommender.v1.RecommenderService.EnrichDocument:output_type -> recommender.v1.EnrichDocumentResponse
	5, // 5: recommender.v1.RecommenderService.TranslateText:output_type -> recommender.v1.TranslateTextResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recommender_v1_recommender_proto_init() }
func file_recommender_v1_recommender_proto_init() {
	if File_recommender_v1_recommender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommender_v1_recommender_proto_rawDesc), len(file_recommender_v1_recommender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommender_v1_recommender_proto_goTypes,
		DependencyIndexes: file_recommender_v1_recommender_proto_depIdxs,
		MessageInfos:      file_recommender_v1_recommender_proto_msgTypes,
	}.Build()
	File_recommender_v1_recommender_proto = out.File
	file_recommender_v1_recommender_proto_goTypes = nil
	file_recommender_v1_recommender_proto_depIdxs = nil
}
