# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from recommender.v1 import recommender_pb2 as recommender_dot_v1_dot_recommender__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommender/v1/recommender_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommenderServiceStub(object):
    """RecommenderService exposes operations of the recommendation engine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/recommender.v1.RecommenderService/Health',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.HealthRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.EnrichDocument = channel.unary_unary(
                '/recommender.v1.RecommenderService/EnrichDocument',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.FromString,
                _registered_method=True)
        self.TranslateText = channel.unary_stream(
                '/recommender.v1.RecommenderService/TranslateText',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.FromString,
                _registered_method=True)


class RecommenderServiceServicer(object):
    """RecommenderService exposes operations of the recommendation engine.
    """

    def Health(self, request, context):
        """Health returns the liveness status of the recommender service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichDocument(self, request, context):
        """EnrichDocument triggers async enrichment (authors, summary, tags, embedding)
        for the given document. Returns immediately with accepted=true; the actual
        processing happens in the background and status is tracked via Redis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateText(self, request, context):
        """TranslateText translates the given text into the target language using LLM,
        streaming back translated chunks as they are generated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.HealthRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.HealthResponse.SerializeToString,
            ),
            'EnrichDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichDocument,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.SerializeToString,
            ),
            'TranslateText': grpc.unary_stream_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommender.v1.RecommenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommender.v1.RecommenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommenderService(object):
    """RecommenderService exposes operations of the recommendation engine.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/Health',
            recommender_dot_v1_dot_recommender__pb2.HealthRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/EnrichDocument',
            recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/recommender.v1.RecommenderService/TranslateText',
            recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
