# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from recommender.v1 import recommender_pb2 as recommender_dot_v1_dot_recommender__pb2


class RecommenderServiceStub(object):
    """RecommenderService exposes operations of the recommendation engine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/recommender.v1.RecommenderService/Health',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.HealthRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.EnrichDocument = channel.unary_unary(
                '/recommender.v1.RecommenderService/EnrichDocument',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.FromString,
                _registered_method=True)
        self.TranslateText = channel.unary_stream(
                '/recommender.v1.RecommenderService/TranslateText',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/recommender.v1.RecommenderService/SemanticSearch',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.RecommendSimilar = channel.unary_unary(
                '/recommender.v1.RecommenderService/RecommendSimilar',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.RecommendSimilarRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.RecommendSimilarResponse.FromString,
                _registered_method=True)
        self.RecommendForUser = channel.unary_unary(
                '/recommender.v1.RecommenderService/RecommendForUser',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.RecommendForUserRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.RecommendForUserResponse.FromString,
                _registered_method=True)
        self.RecommendCollaborators = channel.unary_unary(
                '/recommender.v1.RecommenderService/RecommendCollaborators',
                request_serializer=recommender_dot_v1_dot_recommender__pb2.RecommendCollaboratorsRequest.SerializeToString,
                response_deserializer=recommender_dot_v1_dot_recommender__pb2.RecommendCollaboratorsResponse.FromString,
                _registered_method=True)


class RecommenderServiceServicer(object):
    """RecommenderService exposes operations of the recommendation engine.
    """

    def Health(self, request, context):
        """Health returns the liveness status of the recommender service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichDocument(self, request, context):
        """EnrichDocument triggers async enrichment (authors, summary, tags, embedding)
        for the given document. Returns immediately with accepted=true; the actual
        processing happens in the background and status is tracked via Redis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateText(self, request, context):
        """TranslateText translates the given text into the target language using LLM,
        streaming back translated chunks as they are generated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """SemanticSearch embeds the query text (RETRIEVAL_QUERY task type) and
        searches for similar documents in the vector space (cosine similarity).
        If vector similarity is sparse, fallback to keyword search based on remaining count of results to return.
        Access control is enforced: only private docs owned by the user and
        lab-visible docs in the given lab are considered.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendSimilar(self, request, context):
        """RecommendSimilar returns documents most similar to a source document,
        ranked by vector cosine similarity against the source's stored embedding.
        The source doc is always excluded from results. Access control mirrors
        SemanticSearch: only private docs owned by the caller and lab-visible
        docs in the given lab are candidates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendForUser(self, request, context):
        """RecommendForUser builds a personalized ranked feed for the caller using
        their like history, recent view history, and recent search queries as
        preference signals. Per-signal embeddings are aggregated into a weighted
        profile vector and nearest neighbors are returned. Liked docs are
        excluded from the result set. Access control mirrors RecommendSimilar.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendCollaborators(self, request, context):
        """RecommendCollaborators ranks the caller's lab-mates by interest-profile
        similarity. The caller's profile centroid is built from their liked/viewed
        docs and recent search queries (same shape as RecommendForUser); each
        candidate's centroid is built server-side by averaging the embeddings of
        documents they liked or viewed (no per-candidate Gemini calls). The
        caller is excluded; users with no like/view signals are excluded. Results
        are scoped to a single lab the caller belongs to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.HealthRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.HealthResponse.SerializeToString,
            ),
            'EnrichDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichDocument,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.SerializeToString,
            ),
            'TranslateText': grpc.unary_stream_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.SemanticSearchRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'RecommendSimilar': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendSimilar,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.RecommendSimilarRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.RecommendSimilarResponse.SerializeToString,
            ),
            'RecommendForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendForUser,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.RecommendForUserRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.RecommendForUserResponse.SerializeToString,
            ),
            'RecommendCollaborators': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendCollaborators,
                    request_deserializer=recommender_dot_v1_dot_recommender__pb2.RecommendCollaboratorsRequest.FromString,
                    response_serializer=recommender_dot_v1_dot_recommender__pb2.RecommendCollaboratorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommender.v1.RecommenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommender.v1.RecommenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommenderService(object):
    """RecommenderService exposes operations of the recommendation engine.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/Health',
            recommender_dot_v1_dot_recommender__pb2.HealthRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/EnrichDocument',
            recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/recommender.v1.RecommenderService/TranslateText',
            recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/SemanticSearch',
            recommender_dot_v1_dot_recommender__pb2.SemanticSearchRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendSimilar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/RecommendSimilar',
            recommender_dot_v1_dot_recommender__pb2.RecommendSimilarRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.RecommendSimilarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/RecommendForUser',
            recommender_dot_v1_dot_recommender__pb2.RecommendForUserRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.RecommendForUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendCollaborators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.v1.RecommenderService/RecommendCollaborators',
            recommender_dot_v1_dot_recommender__pb2.RecommendCollaboratorsRequest.SerializeToString,
            recommender_dot_v1_dot_recommender__pb2.RecommendCollaboratorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
