# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommender/v1/recommender.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommender/v1/recommender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n recommender/v1/recommender.proto\x12\x0erecommender.v1\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"9\n\x15\x45nrichDocumentRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\x04\x12\x10\n\x08\x66ile_key\x18\x02 \x01(\t\"*\n\x16\x45nrichDocumentResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"=\n\x14TranslateTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0ftarget_language\x18\x02 \x01(\t\"&\n\x15TranslateTextResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\t2\x9e\x02\n\x12RecommenderService\x12G\n\x06Health\x12\x1d.recommender.v1.HealthRequest\x1a\x1e.recommender.v1.HealthResponse\x12_\n\x0e\x45nrichDocument\x12%.recommender.v1.EnrichDocumentRequest\x1a&.recommender.v1.EnrichDocumentResponse\x12^\n\rTranslateText\x12$.recommender.v1.TranslateTextRequest\x1a%.recommender.v1.TranslateTextResponse0\x01\x42!Z\x1fgateway/internal/pb/recommenderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommender.v1.recommender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037gateway/internal/pb/recommender'
  _globals['_HEALTHREQUEST']._serialized_start=52
  _globals['_HEALTHREQUEST']._serialized_end=67
  _globals['_HEALTHRESPONSE']._serialized_start=69
  _globals['_HEALTHRESPONSE']._serialized_end=118
  _globals['_ENRICHDOCUMENTREQUEST']._serialized_start=120
  _globals['_ENRICHDOCUMENTREQUEST']._serialized_end=177
  _globals['_ENRICHDOCUMENTRESPONSE']._serialized_start=179
  _globals['_ENRICHDOCUMENTRESPONSE']._serialized_end=221
  _globals['_TRANSLATETEXTREQUEST']._serialized_start=223
  _globals['_TRANSLATETEXTREQUEST']._serialized_end=284
  _globals['_TRANSLATETEXTRESPONSE']._serialized_start=286
  _globals['_TRANSLATETEXTRESPONSE']._serialized_end=324
  _globals['_RECOMMENDERSERVICE']._serialized_start=327
  _globals['_RECOMMENDERSERVICE']._serialized_end=613
# @@protoc_insertion_point(module_scope)
