# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from recommender.v1 import recommender_pb2 as recommender_dot_v1_dot_recommender__pb2


class RecommenderServiceStub(object):
  """RecommenderService exposes operations of the recommendation engine.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Health = channel.unary_unary(
        '/recommender.v1.RecommenderService/Health',
        request_serializer=recommender_dot_v1_dot_recommender__pb2.HealthRequest.SerializeToString,
        response_deserializer=recommender_dot_v1_dot_recommender__pb2.HealthResponse.FromString,
        )
    self.EnrichDocument = channel.unary_unary(
        '/recommender.v1.RecommenderService/EnrichDocument',
        request_serializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.SerializeToString,
        response_deserializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.FromString,
        )
    self.TranslateText = channel.unary_stream(
        '/recommender.v1.RecommenderService/TranslateText',
        request_serializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.SerializeToString,
        response_deserializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.FromString,
        )


class RecommenderServiceServicer(object):
  """RecommenderService exposes operations of the recommendation engine.
  """

  def Health(self, request, context):
    """Health returns the liveness status of the recommender service.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnrichDocument(self, request, context):
    """EnrichDocument triggers async enrichment (authors, summary, tags, embedding)
    for the given document. Returns immediately with accepted=true; the actual
    processing happens in the background and status is tracked via Redis.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TranslateText(self, request, context):
    """TranslateText translates the given text into the target language using LLM,
    streaming back translated chunks as they are generated.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommenderServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Health': grpc.unary_unary_rpc_method_handler(
          servicer.Health,
          request_deserializer=recommender_dot_v1_dot_recommender__pb2.HealthRequest.FromString,
          response_serializer=recommender_dot_v1_dot_recommender__pb2.HealthResponse.SerializeToString,
      ),
      'EnrichDocument': grpc.unary_unary_rpc_method_handler(
          servicer.EnrichDocument,
          request_deserializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentRequest.FromString,
          response_serializer=recommender_dot_v1_dot_recommender__pb2.EnrichDocumentResponse.SerializeToString,
      ),
      'TranslateText': grpc.unary_stream_rpc_method_handler(
          servicer.TranslateText,
          request_deserializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextRequest.FromString,
          response_serializer=recommender_dot_v1_dot_recommender__pb2.TranslateTextResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'recommender.v1.RecommenderService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
