host: "0.0.0.0"
port: 50051
max_workers: 10

redis_host: "localhost"
redis_port: 6379
redis_password: ""
redis_db: 0

db_host: "localhost"
db_port: 5432
db_user: "sci_vault"
db_password: "sci_vault_secret"
db_name: "sci_vault"
db_ssl_mode: "disable"
db_timezone: "UTC"

s3_endpoint: "http://localhost:9000"
s3_access_key: "rustfsadmin"
s3_secret_key: "rustfsadmin"
s3_private_bucket: "sci-vault"

# Decides whether to use Vertex AI endpoint or Gemini API endpoint
google_genai_use_vertexai: true
# Obtain one at https://aistudio.google.com/app/api-keys or https://console.cloud.google.com/vertex-ai/studio/settings/api-keys
google_genai_api_key: "YOUR_GEMINI_API_KEY"
